CHANGES.txt
pom.xml

GORA-407 Upgrade restlet dependencies to 2.3.1 for gora-solr

---

gora-solr/src/test/conf/log4j.properties
pom.xml

Dependency upgrade to Solr 4.10.3.

GORA-406 Upgrade Solr dependencies to 4.10.3

---

gora-core/pom.xml
gora-hbase/pom.xml
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseMapping.java
gora-mongodb/pom.xml
gora-shims-hadoop1/src/test/java/org/apache/gora/shims/hadoop1/TestHadoopShim1.java
gora-shims-hadoop2/src/test/java/org/apache/gora/shims/hadoop2/TestHadoopShim2.java
pom.xml

Patch for master branch to address issues with Hadoop Shims

GORA-415 hadoop-client dependency should be optional in gora-core

---

gora-core/src/main/java/org/apache/gora/memory/store/MemStore.java

Hi. 
My previous pull request has a problem. Some tests have failed. I had run only nutch tests, not run gora tests.  I'm sorry for misguiding you about it.  I changed my code and create new pull request. I build sucessfully again. The tests run successfully now. I also test from nutch using TestInjector.java. It is also successful.  GORA-228 GORA-226 NUTCH-1741.

Memstore problems are fixed GORA-228 GORA-226 NUTCH-1741

---

bin/gora
gora-core/pom.xml
gora-core/src/examples/java/org/apache/gora/examples/spark/SparkWordCount.java
gora-core/src/main/java/org/apache/gora/spark/GoraSpark.java
gora-core/src/main/java/org/apache/gora/spark/GoraSparkEngine.java
gora-core/src/test/java/org/apache/gora/mapreduce/MapReduceTestUtils.java
gora-hbase/src/test/java/org/apache/gora/hbase/mapreduce/TestHBaseStoreWordCount.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/mapreduce/TestMongoStoreWordCount.java
gora-tutorial/pom.xml
gora-tutorial/src/main/java/org/apache/gora/tutorial/log/LogAnalyticsSpark.java
pom.xml

Pull request of the work for GSoC project (Spark Backend Support for Gora) for Apache Gora.

Spark Backend Support for Gora (GORA-386)

---

CHANGES.txt
gora-accumulo/src/test/java/org/apache/gora/accumulo/GoraAccumuloTestDriver.java
gora-accumulo/src/test/java/org/apache/gora/accumulo/package-info.java
gora-accumulo/src/test/java/org/apache/gora/accumulo/store/AccumuloStoreTest.java

This issue addresses https://issues.apache.org/jira/browse/GORA-314

GORA-314 Implement TestDriver for AccumuloStoreTest e.g. TODO in class

---

gora-accumulo/pom.xml
gora-cassandra/pom.xml
gora-compiler-cli/pom.xml
gora-compiler/pom.xml
gora-core/pom.xml
gora-core/src/main/java/org/apache/gora/memory/store/MemStore.java
gora-core/src/test/java/org/apache/gora/memory/store/MemStoreTest.java
gora-goraci/pom.xml
gora-hbase/pom.xml
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java
gora-mongodb/pom.xml
gora-solr/pom.xml
gora-tutorial/pom.xml

Hi Folks,
This PR is not 100% yet and I wanted to post it to kick off some conversation regarding behavior of MemStore. First though, this PR
* Fixes issues with [GORA-446](https://issues.apache.org/jira/browse/GORA-446)
* Fixes [GORA-125](https://issues.apache.org/jira/browse/GORA-125) making logging libraries consistent across the codebase and modules.
* Implements logic for query execution and results generation please see MemStore#execute
* Finally, addresses [GORA-240](https://issues.apache.org/jira/browse/GORA-240) We have to @Ignore testDeleteByQueryFields and implement testMemStoreDeleteByQueryFields which is basically the same test however we explicitly set the start and end keys for the Query.
This PR is not 100% yet there are two tests which are currently failing however I …

GORA-240 Tests for MemStore

---

gora-cassandra/src/main/java/org/apache/gora/cassandra/query/CassandraSubColumn.java

This issue addresses https://issues.apache.org/jira/browse/GORA-462

GORA-462 Potential null dereference of serializer in CassandraSubColumn#getFieldValue()

---

gora-cassandra/src/main/java/org/apache/gora/cassandra/query/CassandraSubColumn.java

This issue addresses https://issues.apache.org/jira/browse/GORA-463

GORA-463 Missing assignment in CassandraSubColumn#getUnionSchema()

---

gora-solr-5/pom.xml
gora-solr-5/src/main/java/org/apache/gora/solr/query/SolrQuery.java
gora-solr-5/src/main/java/org/apache/gora/solr/query/SolrResult.java
gora-solr-5/src/main/java/org/apache/gora/solr/store/SolrMapping.java
gora-solr-5/src/main/java/org/apache/gora/solr/store/SolrStore.java
gora-solr-5/src/test/conf/gora-solr-mapping.xml
gora-solr-5/src/test/conf/gora.properties
gora-solr-5/src/test/conf/log4j.properties
gora-solr-5/src/test/conf/solr/Employee/conf/lang/stopwords_en.txt
gora-solr-5/src/test/conf/solr/Employee/conf/protwords.txt
gora-solr-5/src/test/conf/solr/Employee/conf/schema.xml
gora-solr-5/src/test/conf/solr/Employee/conf/solrconfig.xml
gora-solr-5/src/test/conf/solr/Employee/conf/stopwords.txt
gora-solr-5/src/test/conf/solr/Employee/conf/synonyms.txt
gora-solr-5/src/test/conf/solr/WebPage/conf/lang/stopwords_en.txt
gora-solr-5/src/test/conf/solr/WebPage/conf/protwords.txt
gora-solr-5/src/test/conf/solr/WebPage/conf/schema.xml
gora-solr-5/src/test/conf/solr/WebPage/conf/solrconfig.xml
gora-solr-5/src/test/conf/solr/WebPage/conf/stopwords.txt
gora-solr-5/src/test/conf/solr/WebPage/conf/synonyms.txt
gora-solr-5/src/test/conf/solr/collection1/conf/schema.xml
gora-solr-5/src/test/conf/solr/collection1/conf/solrconfig.xml
gora-solr-5/src/test/conf/solr/collection1/core.properties
gora-solr-5/src/test/conf/solr/solr.xml
gora-solr-5/src/test/conf/solr/zoo.cfg
gora-solr-5/src/test/java/org/apache/gora/solr/GoraSolrTestDriver.java
gora-solr-5/src/test/java/org/apache/gora/solr/store/TestSolrStore.java
gora-solr/pom.xml
pom.xml

This issue provides a patch for https://issues.apache.org/jira/browse/GORA-477
This patch was contributed by Aaron Cosand

GORA-477 Add support for Solr 5.x

---

gora-core/pom.xml
gora-core/src/main/java/org/apache/gora/util/TimingUtil.java

spark dependency scope have changed as provided.
Besides javadoc problem is fixed. you can use "mvn javadoc:aggregate"

GORA-445 spark dependency scope have changed as provided

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-infinispan/pom.xml
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanClient.java
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanStore.java

This issues addresses https://issues.apache.org/jira/browse/GORA-479
There are no changes to InfinispanStore.java, this patch merely reformats the code in the correct code formatting. Themain issues was to include the hadoop-client dependency within the module compilation scope.

GORA-479 Various compilation errors in gora-infinispan module

---

bin/gora
gora-jcache/src/main/java/org/apache/gora/jcache/query/package-info.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheEntryListener.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheEntryListenerFactory.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheFactoryBuilder.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheLoader.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheLoaderFactory.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheWriter.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheCacheWriterFactory.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheStore.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/package-info.java
gora-jcache/src/test/java/org/apache/gora/jcache/GoraHazelcastTestDriver.java
gora-jcache/src/test/java/org/apache/gora/jcache/mapreduce/package-info.java
gora-jcache/src/test/java/org/apache/gora/jcache/store/package-info.java
gora-jcache/src/test/resources/gora.properties
gora-tutorial/conf/gora.properties
gora-tutorial/conf/hazelcast-client.xml
gora-tutorial/conf/hazelcast.xml
gora-tutorial/pom.xml
gora-tutorial/src/main/java/org/apache/gora/tutorial/log/DistributedLogManager.java
gora-tutorial/src/main/resources/log4j.properties
pom.xml

@lewismc I have added new tutorial class ( DistributedLogManager.java ) and I have added few fixes for the issues encountered while testing the module. Please go through the sample and let me know what you think and I could add some changes accordingly. If you could give me access to Apache-Gora site, I could add some documentation there as well.

Gora 409 tutorial

---

gora-accumulo/src/main/java/org/apache/gora/accumulo/store/AccumuloStore.java
gora-core/src/main/java/org/apache/gora/util/AvroUtils.java

The code lines have already been in org.apache.gora.util.IOUtils

GORA-487 Edited AccumuloStore.java duplicate code lines

---

pom.xml

GORA-466 avro version upgrade to 1.8.1

---

gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraClient.java

https://issues.apache.org/jira/browse/GORA-499

GORA-499 Fix for a potential NPE

---

gora-compiler-cli/src/main/java/org/apache/gora/compiler/cli/GoraCompilerCLI.java
gora-compiler/src/main/java/org/apache/gora/compiler/GoraCompiler.java
gora-compiler/src/main/java/org/apache/gora/compiler/utils/LicenseHeaders.java

This PR includes enhancements to the gora-compiler as follows.
- add license headers to generated files
- add the ability to compile files in a directory.

GORA-324 Port work done on old GoraCompiler to new GoraCompiler

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java

This PR resolves erroneous error logging in reading HBase mapping file as stated in the issue

GORA-394 Resolve erroneous error logging in reading HBase mapping file

---

gora-core/src/test/java/org/apache/gora/store/DataStoreTestUtil.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java

Fix + enabled ignored Tests in HBase module.
Link to Jira: https://issues.apache.org/jira/browse/GORA-510

GORA-510 Conform Query.setEndKey to inclusive query for HBaseStore

---

gora-accumulo/src/test/java/org/apache/gora/accumulo/store/AccumuloStoreTest.java
gora-cassandra/src/test/java/org/apache/gora/cassandra/store/TestCassandraStore.java
gora-core/src/test/java/org/apache/gora/memory/store/MemStoreTest.java
gora-core/src/test/java/org/apache/gora/memory/store/MemStoreTestDriver.java
gora-core/src/test/java/org/apache/gora/store/DataStoreTestBase.java
gora-couchdb/src/test/java/org/apache/gora/couchdb/store/TestCouchDBStore.java
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java
gora-infinispan/src/test/java/org/apache/gora/infinispan/store/InfinispanStoreTest.java
gora-jcache/src/test/java/org/apache/gora/jcache/store/JCacheGoraDataStoreTest.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStore.java
gora-solr-5/src/test/java/org/apache/gora/solr/store/TestSolrStore.java

This PR removes the deprecated methods from data store test base.

GORA-255 Remove deprecated methods from data store test base

---

gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeMappingBuilder.java
pom.xml

This PR contains changes to update Aerospike java client and remove unsupported policies by the new version.

GORA-515 Update aerospike java client and remove unsupported policies

---

gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeMappingBuilder.java
gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikePolicyConst.java
gora-tutorial/conf/gora-aerospike-mapping.xml

This PR contains changes to update the supported policy configurations as per the 4.0.6 Aerospike java client.
The configurable policies in both [write policy](https://www.aerospike.com/apidocs/java/com/aerospike/client/policy/WritePolicy.html) and [read policy](https://www.aerospike.com/apidocs/java/com/aerospike/client/policy/Policy.html) are made configurable with these changes.

GORA-518 Update the policies as per the 4.0.6 aerospike java client

---

gora-aerospike/src/main/java/org/apache/gora/aerospike/query/AerospikeQuery.java
gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeParameters.java
gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeStore.java
gora-aerospike/src/test/conf/gora.properties
gora-aerospike/src/test/java/org/apache/gora/aerospike/GoraAerospikeTestDriver.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/TestAerospikeStoreCountQuery.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/TestAerospikeStoreMapReduceSerialization.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/TestAerospikeStoreWordCount.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/package-info.java

This PR contains changes for the map reduce based test cases for the aerospike module.

GORA-523 Add map reduce based test cases for aerospike module

---

pom.xml

Hbase version is upgraded to 1.2.6

GORA-531 Upgrade Hbase version to 1.2.6

---

pom.xml

Spark version is upgraded to 2.2.1

GORA-528 Upgrade Spark version to 2.2.1

---

gora-solr/pom.xml
gora-solr/src/main/java/org/apache/gora/solr/store/SolrStore.java
gora-solr/src/test/conf/gora.properties
pom.xml

This PR Upgrade Solr dependency to 8.0.0. Plus all the deprecated methods are removed from usages.

 GORA-554: Upgrade Solr dependency to latest

---

gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanStore.java

Hi @djkevincr,
Can you review and merge this pull request

GORA-545 Fix split size in infinispan store

---

.gitignore
gora-core/src/examples/avro/employeeint.json
gora-core/src/examples/java/org/apache/gora/examples/generated/EmployeeInt.java
gora-lucene/src/main/java/org/apache/gora/lucene/query/LuceneQuery.java
gora-lucene/src/main/java/org/apache/gora/lucene/store/LuceneStore.java
gora-lucene/src/test/conf/gora-lucene-mapping.xml
gora-lucene/src/test/java/org/apache/gora/lucene/store/EmployeeInt.java
gora-lucene/src/test/java/org/apache/gora/lucene/store/TestLuceneStore.java

Infer data type for building range queries. First, check if there is a numeric type if so cast to the appropriate type otherwise set to string datatype.

GORA-555: Improve Lucene query implementation with NumericRangeQuery

---

gora-core/pom.xml
gora-core/src/examples/java/org/apache/gora/examples/WebPageDataCreator.java
gora-core/src/examples/java/org/apache/gora/examples/spark/SparkWordCount.java
gora-core/src/test/java/org/apache/gora/mapreduce/MapReduceTestUtils.java
gora-mongodb/src/test/conf/gora.properties
gora-mongodb/src/test/java/org/apache/gora/mongodb/mapreduce/TestMongoStoreWordCount.java

Fixed Spark Unit test, the main issue was the Spark word count program was not properly written. A flat map functionality was missing.

GORA-565: Enable Spark in Unit Tests

---

gora-core/src/main/java/org/apache/gora/spark/GoraSparkEngine.java
gora-mongodb/src/test/conf/gora.properties
gora-mongodb/src/test/java/org/apache/gora/mongodb/mapreduce/TestMongoStoreWordCount.java

This PR will fix the regression that caused by PR https://github.com/apache/gora/pull/161

GORA-612 : Fix Flink tests for MongoDB module

---

pom.xml

Upgrade the AVRO dependency version from 1.8.1 to 1.8.2.

Upgrade AVRO version to 1.8.2

---

gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/AvroSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/CassandraSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/NativeSerializer.java

Remove duplicated method introduced from https://github.com/apache/gora/pull/156

Remove code duplecate introduced by PR #156

---

gora-tutorial/conf/gora-mongodb-mapping.xml
gora-tutorial/conf/gora.properties
gora-tutorial/pom.xml
pom.xml

This is now completed and tested.

GORA-615: Add gora-mongodb settings to gora-tutorial

---

CHANGES.md
NOTICE.md
README.md
gora-accumulo/pom.xml
gora-aerospike/pom.xml
gora-cassandra/pom.xml
gora-compiler-cli/pom.xml
gora-compiler/pom.xml
gora-core/pom.xml
gora-couchdb/pom.xml
gora-dynamodb/pom.xml
gora-goraci/pom.xml
gora-gradle-plugin/gradle.properties
gora-hbase/pom.xml
gora-ignite/pom.xml
gora-infinispan/pom.xml
gora-jcache/pom.xml
gora-lucene/pom.xml
gora-maven-plugin/pom.xml
gora-mongodb/pom.xml
gora-orientdb/pom.xml
gora-pig/pom.xml
gora-solr/pom.xml
gora-tutorial/pom.xml
pom.xml
sources-dist/pom.xml

PR for bump versions for next development iteration after 0.9 release.

0.9 release branch

---

gora-core/src/test/java/org/apache/gora/store/DataStoreTestUtil.java
gora-hive/pom.xml
gora-hive/src/main/java/org/apache/gora/hive/package-info.java
gora-hive/src/main/java/org/apache/gora/hive/query/HiveQuery.java
gora-hive/src/main/java/org/apache/gora/hive/query/HiveResult.java
gora-hive/src/main/java/org/apache/gora/hive/query/package-info.java
gora-hive/src/main/java/org/apache/gora/hive/store/HiveDataContext.java
gora-hive/src/main/java/org/apache/gora/hive/store/HiveMapping.java
gora-hive/src/main/java/org/apache/gora/hive/store/HiveMappingBuilder.java
gora-hive/src/main/java/org/apache/gora/hive/store/HiveStore.java
gora-hive/src/main/java/org/apache/gora/hive/store/HiveStoreParameters.java
gora-hive/src/main/java/org/apache/gora/hive/store/package-info.java
gora-hive/src/main/java/org/apache/gora/hive/util/HiveQueryBuilder.java
gora-hive/src/main/java/org/apache/gora/hive/util/HiveResultParser.java
gora-hive/src/main/java/org/apache/gora/hive/util/package-info.java
gora-hive/src/test/java/org/apache/gora/hive/GoraHiveTestDriver.java
gora-hive/src/test/java/org/apache/gora/hive/package-info.java
gora-hive/src/test/java/org/apache/gora/hive/store/TestHiveStore.java
gora-hive/src/test/java/org/apache/gora/hive/store/package-info.java
gora-hive/src/test/java/org/apache/gora/hive/util/HiveTestServer.java
gora-hive/src/test/java/org/apache/gora/hive/util/package-info.java
gora-hive/src/test/resources/gora-hive-mapping.xml
gora-hive/src/test/resources/gora.properties
gora-hive/src/test/resources/hive-site.xml
gora-tutorial/pom.xml
pom.xml

Hi All, 
I have implemented an initial version of "gora-hive" data store to support Hive backend in Gora under [GORA-320](https://issues.apache.org/jira/browse/GORA-320)
It will be great if you could review and suggest/comment on any changes to make this a better implementation. Moreover, I appreciate very much if you could run the test profile "hive-with-test" and let me know if any test case is failing. 
Thanks a lot

GORA-320 Hive backend support in Gora

---

gora-kudu/pom.xml
gora-kudu/src/main/java/org/apache/gora/kudu/mapping/Column.java
gora-kudu/src/main/java/org/apache/gora/kudu/mapping/KuduMapping.java
gora-kudu/src/main/java/org/apache/gora/kudu/mapping/KuduMappingBuilder.java
gora-kudu/src/main/java/org/apache/gora/kudu/mapping/package-info.java
gora-kudu/src/main/java/org/apache/gora/kudu/package-info.java
gora-kudu/src/main/java/org/apache/gora/kudu/query/KuduQuery.java
gora-kudu/src/main/java/org/apache/gora/kudu/query/KuduResult.java
gora-kudu/src/main/java/org/apache/gora/kudu/query/package-info.java
gora-kudu/src/main/java/org/apache/gora/kudu/store/KuduStore.java
gora-kudu/src/main/java/org/apache/gora/kudu/store/package-info.java
gora-kudu/src/main/java/org/apache/gora/kudu/utils/KuduBackendConstants.java
gora-kudu/src/main/java/org/apache/gora/kudu/utils/KuduClientUtils.java
gora-kudu/src/main/java/org/apache/gora/kudu/utils/KuduParameters.java
gora-kudu/src/main/java/org/apache/gora/kudu/utils/package-info.java
gora-kudu/src/test/java/org/apache/gora/kudu/GoraKuduTestDriver.java
gora-kudu/src/test/java/org/apache/gora/kudu/mapreduce/KuduStoreMapReduceTest.java
gora-kudu/src/test/java/org/apache/gora/kudu/mapreduce/package-info.java
gora-kudu/src/test/java/org/apache/gora/kudu/package-info.java
gora-kudu/src/test/java/org/apache/gora/kudu/store/TestKuduStore.java
gora-kudu/src/test/java/org/apache/gora/kudu/store/package-info.java
gora-kudu/src/test/resources/gora-kudu-mapping.xml
gora-kudu/src/test/resources/gora.properties
gora-tutorial/conf/gora-kudu-mapping.xml
gora-tutorial/conf/gora.properties
gora-tutorial/pom.xml
pom.xml

[Google Summer of Code 2019]
This PR implements an Apache Kudu datastore for Apache Gora. 
Your feedback would be much appreciated.

GORA-485 Apache Kudu datastore for Gora

---

gora-core/src/test/java/org/apache/gora/store/DataStoreTestBase.java

Fix typo in DataStoreTestBase.

Fix typo in DataStoreTestBase.

---

gora-benchmark/pom.xml
gora-benchmark/src/main/java/org/apache/gora/benchmark/GoraBenchmarkClient.java
gora-benchmark/src/main/java/org/apache/gora/benchmark/GoraBenchmarkUtils.java
gora-benchmark/src/main/java/org/apache/gora/benchmark/generated/User.java
gora-benchmark/src/test/java/org/apache/gora/benchmark/GoraClientTest.java
pom.xml

YCSB dependency is now available in maven central, I have now updated the pom file and the code accordingly.

[GORA-639] Updated YCSB dependency and added developer details to root pom

---

pom.xml

Upgrade mongodb driver version to 3.12.4

Upgrade mongodb driver version

---

gora-solr/pom.xml
pom.xml

Revert "GORA-653 Upgrade solr java driver to version 8.5.0"

---

gora-rethinkdb/pom.xml
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/package-info.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/query/RethinkDBQuery.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/query/RethinkDBResult.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/query/package-info.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/store/RethinkDBMapping.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/store/RethinkDBMappingBuilder.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/store/RethinkDBStore.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/store/RethinkDBStoreParameters.java
gora-rethinkdb/src/main/java/org/apache/gora/rethinkdb/store/package-info.java
gora-rethinkdb/src/test/java/org/apache/gora/rethinkdb/RethinkDBTestDriver.java
gora-rethinkdb/src/test/java/org/apache/gora/rethinkdb/package-info.java
gora-rethinkdb/src/test/java/org/apache/gora/rethinkdb/store/RethinkDBGoraDataStoreTest.java
gora-rethinkdb/src/test/java/org/apache/gora/rethinkdb/store/RethinkDBStartupWaitStrategy.java
gora-rethinkdb/src/test/java/org/apache/gora/rethinkdb/store/package-info.java
gora-rethinkdb/src/test/resources/gora-rethinkdb-mapping.xml
gora-rethinkdb/src/test/resources/gora.properties
pom.xml

This represents final PR for RethinkDB Datastore Implementation for Apache Gora. This work is done as my GSOC 2020 project for Apache.

[GORA-655] RethinkDB datastore Implementation 

---

gora-kudu/pom.xml
gora-kudu/src/main/java/org/apache/gora/kudu/store/KuduStoreMetadataAnalyzer.java
gora-kudu/src/main/java/org/apache/gora/kudu/store/KuduTableMetadata.java
gora-kudu/src/test/java/org/apache/gora/kudu/store/TestKuduStore.java

Add metadata analyzer feature in KUDU for GoraExplorer support.

Add support for the Kudu datastore in GoraExplorer

---

.asf.yaml

Addresses https://issues.apache.org/jira/browse/GORA-686

GORA-686 Add .asf.yaml file to Gora repository

---

pom.xml

Upgrade spark to 2.4.8.    Ran gora-core, gora-hbase tests with jdk8, passed.

Upgrade spark to 2.4.8
