pom.xml

I _think_ that this should permit us to publish the Hadoop 1.X compatible artifacts as defined within [GORA-417](https://issues.apache.org/jira/browse/GORA-417).
Dy default the Hadoop 2 profile is active.
The PR also includes the removal of a bunch of commented out dependencies as well as minor formatting corrections.

GORA-417 Deploy Hadoop-1 compatible binaries for Apache Gora

---

gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraStore.java
gora-compiler/src/main/java/org/apache/gora/compiler/GoraCompiler.java
gora-solr/src/main/java/org/apache/gora/solr/store/SolrStore.java

Non-final public static fields can be changed by external classes (by a malicious code or accidentally).

GORA-433 Non-Final Public Static Fields Should Be Final

---

gora-solr/src/main/java/org/apache/gora/solr/store/SolrStore.java

Fix for uncommitted documents which are at last buffer when buffer is not equal to default commit size.

GORA-434 Documents are Not Committed Into Solr Store

---

gora-core/src/main/java/org/apache/gora/util/IOUtils.java

Erroneous exception message: "cannot write to DataOutput of instance:" at readObject method of IOUtils.java is fixed.

GORA-438 Erroneous Exception Message at IOUtils.java

---

CHANGES.txt
gora-core/src/main/java/org/apache/gora/filter/FilterList.java
gora-core/src/main/java/org/apache/gora/filter/FilterOp.java
gora-core/src/main/java/org/apache/gora/filter/MapFieldValueFilter.java
gora-core/src/main/java/org/apache/gora/filter/SingleFieldValueFilter.java
gora-core/src/test/java/org/apache/gora/filter/TestFilterList.java

This pull request implements the FilterList#filter function to provide us with both Operator.MUST_PASS_ALL (AND) and Operator.MUST_PASS_ONE (OR) query functionality.
It also introduces a new test class TestFilterList to test basic FilterList functionality as well as both Operator.MUST_PASS_ALL (AND) and Operator.MUST_PASS_ONE (OR) query functionality.

GORA-454 Implement FilterList tests

---

gora-maven-plugin/.gitignore
gora-maven-plugin/README.md
gora-maven-plugin/pom.xml
gora-maven-plugin/src/main/java/org/apache/gora/maven/plugin/AbstractGoraMojo.java
gora-maven-plugin/src/main/java/org/apache/gora/maven/plugin/GenerateMojo.java
gora-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
pom.xml

This issue addresses [GORA-277](https://issues.apache.org/jira/browse/GORA-277) by combining work by both Gerhard Gossen and Viacheslav Dobromyslov in order to produce the very useful gora-maven-plugin module for us to publish and use for easily generating Gora Java beans. 
I've [reached out](https://github.com/dobromyslov/gora-maven-plugin/issues/1) to @dobromyslov, hopefully the move to merge this code into Gora master will be welcomed.

GORA-277 Create gora-maven-plugin

---

gora-accumulo/src/test/java/org/apache/gora/accumulo/store/PartitionTest.java
gora-core/src/test/java/org/apache/gora/util/TestWritableUtils.java

When a DataOutputStream instance wraps an underlying ByteArrayOutputStream instance,
it is recommended to flush or close the DataOutputStream before invoking the underlying instances's toByteArray(). Also, it is a good practice to call flush/close explicitly as mentioned for example [here](http://stackoverflow.com/questions/2984538/how-to-use-bytearrayoutputstream-and-dataoutputstream-simultaneously-java).
This pull request add a flush method before toByteArray. I have also added a [Jira Issue](https://issues.apache.org/jira/browse/GORA-467).

GORA-467 Flushing DataOutputStream before calling toByteArray on the underlying ByteArrayOutputStream

---

gora-core/src/test/java/org/apache/gora/GoraTestDriver.java
gora-couchdb/pom.xml
gora-couchdb/src/main/java/org/apache/gora/couchdb/query/CouchDBQuery.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/query/CouchDBResult.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBMapping.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBMappingBuilder.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBParameters.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBStore.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/util/CouchDBObjectMapperFactory.java
gora-couchdb/src/test/conf/gora-couchdb-mapping.xml
gora-couchdb/src/test/conf/gora.properties
gora-couchdb/src/test/java/org/apache/gora/couchdb/GoraCouchDBTestDriver.java
gora-couchdb/src/test/java/org/apache/gora/couchdb/package-info.java
gora-couchdb/src/test/java/org/apache/gora/couchdb/store/TestCouchDBStore.java
gora-goraci/src/main/resources/gora-couchdb-mapping.xml
gora-goraci/src/main/resources/gora.properties
gora-tutorial/conf/gora-couchdb-mapping.xml
gora-tutorial/conf/gora.properties
gora-tutorial/pom.xml
pom.xml

This pull request is for GORA-437. I developed couchdb store for gora. I added javadocs and test codes. The tests required couchdb instance. But I wondered how to start couchdb server programmatically using java. So, I sent an email to couchDB userlist. They suggest that using docker. Then I use docker programmaticaly with  https://github.com/testcontainers/testcontainers-java . All test cases passed with this approach. But this caused dependece to **docker** and **jdk 1.8** . So this pull request doesn't merge to master. 
We should look another solution. Maybe using mockito for testing or another idea?
All tests are passed on my local. I ignored 3 tests. You can see them in my test code.

GORA-437 implement couchdb datastore

---

gora-core/src/main/java/org/apache/gora/util/AvroUtils.java
gora-core/src/main/java/org/apache/gora/util/ByteUtils.java
gora-core/src/main/java/org/apache/gora/util/ClassLoadingUtils.java
gora-core/src/main/java/org/apache/gora/util/IOUtils.java
gora-core/src/main/java/org/apache/gora/util/NodeWalker.java
gora-core/src/main/java/org/apache/gora/util/ReflectionUtils.java
gora-core/src/main/java/org/apache/gora/util/StringUtils.java
gora-core/src/main/java/org/apache/gora/util/VersionInfo.java
pom.xml

Seems like there are many javadoc related issues are still there in the code base. Will work on the rest once got some time. :) Also I have excluded generating javadocs for generated class packages.

GORA-501 Fix Javadoc for JDK1.8

---

gora-core/src/test/java/org/apache/gora/store/DataStoreTestUtil.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseTableConnection.java
gora-hbase/src/test/conf/hbase-site.xml
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java
pom.xml

Work in progress for updating gora to 1.2.2. I also looked at @lewismc 's work ;)
All of tests pass when run individually, but when run as a whole some of them fail. I think this is because of the BufferedMutator and taking longer than it should. The usage of the BufferedMutator is like setting autoFlush=False which then makes sense to actually use our Flush method.
The weird thing is that if we use the regular Table and do the operations synchronously all tests pass always. This would be like setting autoFlush=True. The problem with using this option is that Gora wouldn't be batching any operations and just passing them down.
Maybe someone has an idea on how to check for BufferedMutator to be done (?)

GORA-443 Upgrade HBase to 1.2.0

---

gora-core/src/test/java/org/apache/gora/store/DataStoreTestUtil.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseTableConnection.java

https://github.com/apache/gora/pull/86
> All of tests pass when run individually, but when run as a whole some of them fail.
I also encountered the same problem.
~~I think this is because of AsyncProcess asynchronously process a series of mutations.~~
~~I made this fix as a possible solution.~~ 
Required more investigation.
Anyway, If there is anything I can contribute to something, I definitely want to work for GORA or NUTCH :)

Fixed issue GORA-443

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java

Couldn't be deleted the column with addColumn because addColumn is Delete the specified version of the specified column.
I think this will be a solution to GORA-472.

Fixed issue GORA-472

---

README.md
gora-maven-plugin/README.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/test/conf/gora-hbase-mapping-mismatch.xml
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java

This PR resolves GORA-512 by adding the necessary exception for erroneous mapping files and a test case to capture it.

GORA-512 Add HBase configuration exception for erroneous mapping file and test

---

gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeParameters.java
gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeStore.java
gora-tutorial/conf/gora.properties

This PR contains changes to validate against a server that has restricted access with basic authentication. 
Note 
This functionality is not tested as the security enabling can be only done in the [enterprise edition](http://www.aerospike.com/docs/guide/security/index.html) of Aerospike

GORA-519 Add support for connecting to authenticated servers in aerospike module

---

gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeStore.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/store/TestAerospikeStore.java

This PR contains changes to retrieve the partitions in aerospike module.
As Aerospike does not support query key ranges as at the moment, only the single partition is retrieved with this method. In addition this PR fixes the test case related to getPartitions method and formats the Aerospike test store.

GORA-520 Add support to retrieve partitions in aerospike module

---

gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeStore.java

This PR contains changes to update the Put method.
Currently if the key is already existing, the whole record is deleted before adding the new record. This behavior results removing the needed fields, if the new addition only updates certain fields. With this fix, it deletes the record only if certain fields are removed with the new update.

GORA-522 Fix the put method in aerospike module

---

gora-core/src/main/java/org/apache/gora/persistency/impl/PersistentBase.java

Field index 0 is always considered as clean even if it is dirty.

Fixed issue GORA-503

---

gora-accumulo/src/main/java/org/apache/gora/accumulo/store/AccumuloStore.java
gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeStore.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/AvroSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/CassandraSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/NativeSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraStore.java
gora-core/src/main/java/org/apache/gora/avro/store/AvroStore.java
gora-core/src/main/java/org/apache/gora/avro/store/DataFileAvroStore.java
gora-core/src/main/java/org/apache/gora/memory/store/MemStore.java
gora-core/src/main/java/org/apache/gora/persistency/impl/BeanFactoryImpl.java
gora-core/src/main/java/org/apache/gora/store/impl/DataStoreBase.java
gora-core/src/main/java/org/apache/gora/store/impl/FileBackedDataStoreBase.java
gora-core/src/main/java/org/apache/gora/store/ws/impl/WSBackedDataStoreBase.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBStore.java
gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBNativeStore.java
gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanClient.java
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanStore.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheStore.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStore.java
gora-orientdb/src/main/java/org/apache/gora/orientdb/store/OrientDBStore.java
gora-solr/src/main/java/org/apache/gora/solr/query/SolrResult.java
gora-solr/src/main/java/org/apache/gora/solr/store/SolrStore.java

Hi!
In this patch basically I removed the redundand "logging + throw" when the log message is the same as in the exception.
Sorry for the mess of two pull requests :(
Please comment anything you find that don't convice you.
Thanks!
https://issues.apache.org/jira/browse/GORA-530

GORA-530: Removed redundant logging on several try/catch

---

gora-accumulo/src/main/java/org/apache/gora/accumulo/store/AccumuloStore.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraClient.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraStore.java
gora-core/src/main/java/org/apache/gora/persistency/impl/BeanFactoryImpl.java
gora-core/src/main/java/org/apache/gora/persistency/ws/impl/BeanFactoryWSImpl.java
gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBNativeStore.java
gora-goraci/src/main/java/org/apache/gora/goraci/chef/ChefSoftwareProvisioning.java
gora-goraci/src/main/java/org/apache/gora/goraci/rackspace/RackspaceOrchestration.java
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanClient.java
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanStore.java

When using reflexion use `getDeclaredConstructor().newInstance()` instead of `Class::newInstance` because it may throw undeclared checked exceptions.

GORA-536: Avoid calling Class#newInstance

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseMapping.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseTableConnection.java
gora-hbase/src/main/java/org/apache/gora/hbase/util/DefaultFactory.java
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java
gora-hbase/src/test/java/org/apache/gora/hbase/util/HBaseClusterSingleton.java
pom.xml

This PR includes HBase Version upgrade to 2.1.1. I have also avoided all the deprecated methods usages.
I went thought PR https://github.com/apache/gora/pull/86 and I guess we need check whether we can get rid of changes introduced by https://github.com/apache/gora/pull/95 after issue https://issues.apache.org/jira/browse/HBASE-8770 is fixed from HBase.

GORA-534 Upgrade HBase to 2.1.1

---

pom.xml

Update <scm> section for parent pom after the move to gitbox.apache.org.

GORA-550: Update POM on the move to gitbox.

---

gora-core/src/main/java/org/apache/gora/persistency/impl/PersistentBase.java

This is no longer required since SpecificRecordBase extends java.io.Externalizable with AVRO upgrade.

GORA-549: Remove PersistentBase extending java.io.Externalizable

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStoreMetadataAnalyzer.java

Remove deprecated API calls from HbaseStore and HBaseStoreMetadataAnalyzer classes.

GORA-564: Remove deprecated method usages of HBase module after upgrading to 2

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseTableConnection.java
gora-hbase/src/main/java/org/apache/gora/hbase/util/HBaseByteInterface.java
gora-hbase/src/test/conf/gora.properties
gora-hbase/src/test/java/org/apache/gora/hbase/mapreduce/TestHBaseStoreCountQuery.java
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java
gora-hbase/src/test/java/org/apache/gora/hbase/util/TestHBaseByteInterface.java

Fix various issues such as resource closing, auto flush etc. https://issues.apache.org/jira/browse/HBASE-2256 -  main concern here is sometime back we addressed this issue, by differentiating timestamp values for HBase put/delete in put (K key, V value). However it seems, sometimes this fails intermittently. I have used atomic row update  - RowMutations instead of buffered mutator and the tests seems to passing solidly.

GORA-611: Fix intermittent test failures with HBase module

---

gora-core/src/examples/java/org/apache/gora/examples/mapreduce/MapReduceSerialization.java
gora-core/src/examples/java/org/apache/gora/examples/mapreduce/QueryCounter.java
gora-core/src/examples/java/org/apache/gora/examples/mapreduce/WordCount.java
gora-core/src/main/java/org/apache/gora/flink/GoraFlinkEngine.java
gora-core/src/main/java/org/apache/gora/mapreduce/NullOutputCommitter.java
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStore.java

This PR removes deprecated method usages inside gora-core module.

GORA-613 Remove deprecated usages in gora-core module

---

gora-accumulo/src/main/java/org/apache/gora/accumulo/store/AccumuloStore.java
gora-aerospike/src/main/java/org/apache/gora/aerospike/store/AerospikeStore.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/AvroSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/CassandraQueryFactory.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/CassandraSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/serializers/NativeSerializer.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraStore.java
gora-core/src/main/java/org/apache/gora/avro/store/AvroStore.java
gora-core/src/main/java/org/apache/gora/memory/store/MemStore.java
gora-core/src/main/java/org/apache/gora/store/DataStore.java
gora-core/src/main/java/org/apache/gora/store/impl/DataStoreBase.java
gora-core/src/test/java/org/apache/gora/mock/store/MockDataStore.java
gora-core/src/test/java/org/apache/gora/store/DataStoreTestBase.java
gora-core/src/test/java/org/apache/gora/store/DataStoreTestUtil.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBStore.java
gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBAvroStore.java
gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBNativeStore.java
gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-ignite/src/main/java/org/apache/gora/ignite/store/IgniteStore.java
gora-ignite/src/main/java/org/apache/gora/ignite/utils/IgniteSQLBuilder.java
gora-infinispan/src/main/java/org/apache/gora/infinispan/store/InfinispanStore.java
gora-jcache/src/main/java/org/apache/gora/jcache/store/JCacheStore.java
gora-lucene/src/main/java/org/apache/gora/lucene/store/LuceneStore.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStore.java
gora-orientdb/src/main/java/org/apache/gora/orientdb/store/OrientDBStore.java
gora-solr/src/main/java/org/apache/gora/solr/store/SolrStore.java

Adds a **exists(key)** method to the DataStores.
- Custom implementations for all backends.
- Two new tests for: operability and benchmark.
Your feedback would be appreciated :)

GORA 411 - Add exists(key) to DataStore interface

---

gora-tutorial/pom.xml

The issue was the conflict among 
1. log4j-slf4j-impl-2.11.0.jar
2. slf4j-simple-1.6.6.jar
3. slf4j-log4j12-1.6.6.jar
and first two jars were taken from gora-couchdb and gora-solr. 
As a fix, those jars excluded in gora-tutorial/pom.xml dependencies

GORA 616 Fix Multiple slf4j conflict issue

---

pom.xml

Unnecessary usages, duplicate runs are removed from releases. maven-gpg-plugin already inherited from Apache Parent pom version 21.

Fix GORA-618 gpg and checksum maven plugin issues

---

gora-compiler-cli/src/main/java/org/apache/gora/compiler/cli/GoraCompilerCLI.java

This PR updates the cli output for --help and output when no arguments specified for `goracompiler`.
**Current output** - 
```
mlpj@mlpj-Inspiron-3543:~/Documents/gora$ bin/gora goracompiler --help
INFO  cli.GoraCompilerCLI            - Usage: gora-compiler ( -h | --help ) | (<input> [<input>...] <output> [-license <id>])
ERROR cli.GoraCompilerCLI            - License header options include;
ASLv2   (Apache Software License v2.0) 
AGPLv3  (GNU Affero General Public License) 
CDDLv1  (Common Development and Distribution License v1.0) 
FDLv13  (GNU Free Documentation License v1.3) 
GPLv1   (GNU General Public License v1.0) 
GPLv2   (GNU General Public License v2.0) 
GPLv3   (GNU General Public License v3.0) 
LGPLv21 (GNU Lesser General Public License v2.1) 
LGPLv3  (GNU Lesser General …
```

GORA-456: No help when GoraCompilerCli is invoked without parameters

---

gora-pig/src/test/resources/gora.properties

Eg:- gora.hbasestore.hbase.client.autoflush.enabled=true

GORA-620: Migrate autoflush parameter after HBase refactor

---

gora-solr/pom.xml
gora-tutorial/pom.xml

We observed there are number of log4j dependencies added to classpath due to transitivity.
Until we do a proper log4j upgrade, we should remove log4j 2 dependencies from classpath inheriting from transitive dependencies. Current we have log4j version 1.x.x defined at parent pom and it is used over the entire set of modules. Similar issues reported at [1] due to multiple log4j implementations.
[1] https://issues.apache.org/jira/browse/GORA-616

GORA-621: Remove log4j 2 transitive dependencies from solr core

---

pom.xml

This pr addresses https://issues.apache.org/jira/browse/GORA-622

GORA-622 maven-assemly-plugin complains that group id is too big and fails build on macOS Mojave 10.14.6 (18G87)

---

gora-cassandra/src/examples/java/org/apache/gora/cassandra/example/generated/AvroSerialization/CassandraKey.java
gora-cassandra/src/examples/java/org/apache/gora/cassandra/example/generated/AvroSerialization/CassandraRecord.java
gora-compiler/src/main/velocity/org/apache/gora/compiler/templates/record.vm
gora-core/src/examples/java/org/apache/gora/examples/generated/Employee.java
gora-core/src/examples/java/org/apache/gora/examples/generated/EmployeeInt.java
gora-core/src/examples/java/org/apache/gora/examples/generated/ImmutableFields.java
gora-core/src/examples/java/org/apache/gora/examples/generated/Metadata.java
gora-core/src/examples/java/org/apache/gora/examples/generated/TokenDatum.java
gora-core/src/examples/java/org/apache/gora/examples/generated/V2.java
gora-core/src/examples/java/org/apache/gora/examples/generated/WebPage.java
gora-goraci/src/main/java/org/apache/gora/goraci/generated/CINode.java
gora-goraci/src/main/java/org/apache/gora/goraci/generated/Flushed.java
gora-tutorial/src/main/java/org/apache/gora/tutorial/log/generated/MetricDatum.java
gora-tutorial/src/main/java/org/apache/gora/tutorial/log/generated/Pageview.java

Correct GoraCompiler formatting for embedded Tombstone class.
Using spaces instead of tabs.

GORA-396 Correct GoraCompiler formatting for embedded Tombstone class

---

gora-hive/src/test/resources/gora-hive-mapping.xml

Hive data store is failing testObjectFieldValue test case as the employee mapping of hive test mapping file doesn't contain a "value" field.
tracked in GORA-631

GORA-631 Fix Hive datastore fails testObjectFieldValue test case

---

gora-cassandra/pom.xml

As discussed in [GORA-623](https://issues.apache.org/jira/projects/GORA/issues/GORA-623), we should avoid generating JavaDocs for generated classes and this patch will add generated classes of Cassandra as test sources. (We have done the same for gora-core)
Build verified.
To address compiler issue [GORA-632](https://issues.apache.org/jira/projects/GORA/issues/GORA-632) is created

GORA-623 Javadoc build fails with Gora master branch

---

gora-couchdb/pom.xml
gora-solr/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

gora-tutorial/conf/gora-ignite-mapping.xml
gora-tutorial/conf/gora.properties
gora-tutorial/pom.xml
gora-tutorial/src/main/resources/META-INF/config/java.util.logging.properties
pom.xml

Add support for Ignite in the gora-tutorial module.
As part of my experiments with Gora, I tried to add ignite in the tutorial module using other other databases as example. Please let me know if I missed something.

[GORA-638] Add gora-ignite into the gora-tutorial module

---

gora-dynamodb/src/main/java/org/apache/gora/dynamodb/store/DynamoDBStore.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java

This PR will change the `HBaseStore` and `DynamoDBStore` to use `DataStoreFactory.getMappingFile()` method, when retrieving the filename for the mapping file from the properties file.
`CassandraStore` is already fixed.

GORA-271 Make consistent across datastores the way of getting the mapping filename

---

gora-mongodb/src/main/java/org/apache/gora/mongodb/filters/DefaultFactory.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/filters/FilterFactory.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/filters/MongoFilterUtil.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/query/MongoDBQuery.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/query/MongoDBResult.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStore.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStoreParameters.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/utils/BSONDecorator.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/utils/Utf8Codec.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/filters/DefaultFactoryTest.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStore.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/utils/TestBSONDecorator.java

- Use new `MongoDatabase` and `MongoCollection` API as described on [Databases and Collections](http://mongodb.github.io/mongo-java-driver/3.12/driver/tutorials/databases-collections/)
- Use [Codec and CodecRegistry](http://mongodb.github.io/mongo-java-driver/3.12/bson/codecs/) interface instead of `DefaultDBEncoder`
- `MongoFilterUtil`: Avoid changing query passed as reference so adapted to return an `Optional` with subfilter to apply
- Use `org.bson.Document` as container everywhere (replace `DBObject`)
- Use [Filters](http://mongodb.github.io/mongo-java-driver/3.12/builders/filters/) and [Projections](http://mongodb.github.io/mongo-java-driver/3.12/builders/projections/) helper methods to facilitate the creation of filter documents
- `MongoDBResult`: pass `cursor` and `size` as …

GORA-649 Replace usage of deprecated API of MongoDB driver

---

gora-benchmark/pom.xml
gora-benchmark/src/test/java/org/apache/gora/benchmark/GoraClientTest.java
gora-mongodb/pom.xml
gora-mongodb/src/test/java/org/apache/gora/mongodb/GoraMongodbTestDriver.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/MongoContainer.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/authentications/GoraMongodbAuthenticationTestDriver.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/authentications/PLAIN_AuthenticationTest.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/authentications/SCRAM_SHA_1_AuthenticationTest.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/mapreduce/GoraMongoMapredTest.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStore34.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStore36.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStore40.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStore42.java
pom.xml

- Update `gora-mongodb/pom.xml` to use testcontainers    
* Remove `de.flapdoodle.embed.mongo` dependency
* Remove `mongo.embed.version` property
* Add `org.testcontainers` dependency
- Create `MongoContainer` and it as a JUnit `@ClassRule`
- Add new test for MongoDB 4.2
- Refactor `GoraMongodbTestDriver`  
* Provided container (passed in constructor) to configure Gora properties
- Update `gora-benchmark/pom.xml` to depends on `gora-mongodb:test-jar`
We can import MongoContainer in GoraClientTest
(with fixed MongoDB port on localhost)
- Refactor `GoraMongodbAuthenticationTestDriver`
* Use MongoDB docker container feature to initialize superuser (via environment variables)
* Pass `--auth` and `--setParameter authenticationMechanisms` as commands
* Use mongo shell CLI - inside container - …

GORA-647 Use Testcontainers for MongoDB integration tests

---

gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraClient.java
gora-cassandra/src/main/java/org/apache/gora/cassandra/store/CassandraStoreParameters.java
gora-compiler/src/main/java/org/apache/gora/compiler/GoraCompiler.java
gora-couchdb/src/main/java/org/apache/gora/couchdb/store/CouchDBStore.java
gora-goraci/src/main/java/org/apache/gora/goraci/Generator.java
gora-goraci/src/main/java/org/apache/gora/goraci/Verify.java
gora-goraci/src/main/java/org/apache/gora/goraci/chef/ChefSoftwareProvisioning.java
gora-goraci/src/main/java/org/apache/gora/goraci/rackspace/RackspaceOrchestration.java
gora-infinispan/src/test/java/org/apache/gora/infinispan/SimulationDriver.java
gora-tutorial/src/main/java/org/apache/gora/tutorial/log/LogAnalytics.java

There are a couple of issues I faced with:
1) Is it ok to remove `allowRemoteDCsForLocalConsistencyLevel` completely like I did? The docs say "DC failover shouldn't be done in the driver, which does not have the necessary context to know what makes sense considering application semantics", so it probably does not make sense to keep this as an option in gora.
2) Datastax developers [decided to remove](https://docs.datastax.com/en/developer/java-driver/3.5/upgrade_guide/#3-5-0) `DowngradingConsistencyRetryPolicy` adding that users will now have to implement this logic themselves. It is probably possible to implement something analogous to their [example](https://github.com/datastax/java-driver/blob/3.x/driver-examples/src/main/java/com/datastax/driver/examples/retry/DowngradingRetry.java), …

GORA-430 Address use of deprecated API's

---

Jenkinsfile
gora-aerospike/src/test/java/org/apache/gora/aerospike/GoraAerospikeTestDriver.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/TestAerospikeStoreCountQuery.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/TestAerospikeStoreMapReduceSerialization.java
gora-aerospike/src/test/java/org/apache/gora/aerospike/mapreduce/TestAerospikeStoreWordCount.java
gora-rethinkdb/src/test/java/org/apache/gora/rethinkdb/RethinkDBTestDriver.java

Here is my proposal for a [Jenkinsfile](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/) for Apache Gora.
There is two stages in this pipeline:
- **Build** which trigger `mvn clean install` targets
- **Test** which trigger `mvn verify` and transform any failure as UNSTABLE status for Jenkins job
I've also improved _Aerospike_ and _RethinkDB_ tests.
I'm using [container's ip address returned by _testcontainer_](https://www.testcontainers.org/features/networking/#getting-the-container-host) instead of `localhost` to support use case where Jenkins is running inside Docker (aka Docker in Docker)
Closes : https://issues.apache.org/jira/browse/GORA-668

GORA-668 Add Jenkinsfile

---

gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseMapping.java
gora-hbase/src/main/java/org/apache/gora/hbase/store/HBaseStore.java
gora-hbase/src/test/java/org/apache/gora/hbase/store/TestHBaseStoreMappingFromProperties.java

This PR still uses DataStoreFactory.getMappingFile() method, when retrieving the filename for the mapping file from the properties file, but also allows to load mappings from properties instead of only from files.

GORA-667 Revert GORA-271 changes in hbase-store 

---

gora-ignite/src/main/java/org/apache/gora/ignite/store/IgniteMappingBuilder.java
gora-ignite/src/main/java/org/apache/gora/ignite/store/IgniteStore.java
gora-ignite/src/main/java/org/apache/gora/ignite/store/IgniteStoreMetadataAnalyzer.java
gora-ignite/src/main/java/org/apache/gora/ignite/store/IgniteTableMetadata.java
gora-ignite/src/main/java/org/apache/gora/ignite/utils/IgniteSQLBuilder.java
gora-ignite/src/test/java/org/apache/gora/ignite/store/TestIgniteStore.java
pom.xml

To add support for Apache Ignite in Gora Explorer the mapping XML must be read from gora.mapping in the same way as is implemented in the Kudu datastore.

[GORA-665] - Add support for the Ignite datastore in GoraExplorer

---

gora-core/src/main/java/org/apache/gora/store/DataStoreMetadataFactory.java
gora-core/src/main/java/org/apache/gora/store/impl/DataStoreMetadataAnalyzer.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoMapping.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoMappingBuilder.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStore.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStoreCollectionMetadata.java
gora-mongodb/src/main/java/org/apache/gora/mongodb/store/MongoStoreMetadataAnalyzer.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoMappingBuilder.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStoreMappingFromProperties.java
gora-mongodb/src/test/java/org/apache/gora/mongodb/store/TestMongoStoreMetadataAnalyzer.java

Since MongoDB has collections instead of tables and these collections do not necessarily have a schema, I decided to use random collection document's key set.

GORA-557 Add support for MongoDB to GoraExplorer

---

.github/workflows/master-pr-build.yml
.github/workflows/master-push-build.yml
gora-couchdb/pom.xml
gora-couchdb/src/main/java/org/apache/gora/couchdb/util/CouchDBObjectMapperFactory.java
pom.xml

* As described on testcontainers/testcontainers-java#3574, we need to upgrade to **testcontainers 1.15.2** in order for tests to run on recent Docker runtimes
>    Ok, "filter by image name" query parameter in /images/json got removed on Docker's API.
>    Although the query param was deprecated (I wish we could run Docker in a strict API mode - will explore)
>    Sorry for this. We will release a hotfix ASAP. Meanwhile, consider pre-pulling testcontainers/ryuk:0.3.0 and alpine:3.5
* Upgrade Jackson dependency of `gora-couchdb` module because it depends on **outdated (and unsecured)** release + **trigger NoSuchMethodError** with new testcontainers 1.15.2 (see testcontainers/testcontainers-java#3937). Import `jackson-bom` 2.12.1 in dependency management of main `pom.xml`
* Also update …

GORA-674: upgrade testcontainers to 1.15.2

---

gora-geode/pom.xml
gora-geode/src/main/java/org/apache/gora/geode/query/GeodeQuery.java
gora-geode/src/main/java/org/apache/gora/geode/query/GeodeResult.java
gora-geode/src/main/java/org/apache/gora/geode/store/GeodeStore.java
gora-geode/src/main/java/org/apache/gora/geode/store/GeodeStoreParameters.java
gora-geode/src/test/conf/gora.properties
gora-geode/src/test/java/org/apache/gora/geode/GeodeStartupLogWaitStrategy.java
gora-geode/src/test/java/org/apache/gora/geode/GoraGeodeTestDriver.java
gora-geode/src/test/java/store/TestGeodeStore.java
pom.xml

[IN-PROGRESS] GORA-698 Geode DataStore
